
export default events = {
  BLOCKS: 'BLOCKS',
  FREQUENCIES: 'FREQUENCIES',
  BATTERY_VOLTAGE: 'BATTERY_VOLTAGE',
  BATTERY_TYPE: 'BATTERY_TYPE',
  PILOT_TONE: 'PILOT_TONE',
  RF_LEVEL: 'RF_LEVEL',
  OUT_LEVEL: "OUT_LEVEL",
  ID: 'ID',
  SCAN_START: "SCAN_START" ,
  SCAN_STOP: "SCAN_STOP" ,
  SCAN_POLL: "SCAN_POLL",
  SET_CHANGE: "SET_CHANGE",
  RX_PRESENT: "RX_PRESENT",
  RX_LABEL: "RX_LABEL"
}